### PR TITLE
Fix SBOM generation inconsistency, take 2

### LINKED ISSUE #64: SBOM inconsistency gok sbom vs gok overwrite/update
Turns out that https://github.com/gokrazy/tools/pull/61 only fixed the SBOM inconsistencies that were caused by config.Struct pointers and by the Sudo flag, that was set [here](https://github.com/gokrazy/tools/pull/61/files#diff-e92c79e77d56e8f8dca8f4a40e1a942331870e428ee4db4a2f4c5b1b3ef29843L1008-L1011).
They did not fix the diff that is generated from the other fields in the `config.InternalCompatibilityFlags`, which I didn't realise, are set depending on the update mode.

- If `gok sbom` is used, no `config.InternalCompatibilityFlags` are set.
- If `gok overwrite --full` is used `config.InternalCompatibilityFlags.Overwrite` and `config.InternalCompatibilityFlags.TargetStorageBytes` are set
- If `gok overwrite --gaf` is used, nothing is set
- If `gok update` is used, `config.InternalCompatibilityFlags.Udpdate` (optionally Insecure, Testboot) is set.

These end up being accounted for when the `config.Struct` is stringyfied and formatted in hex, influencing the hash value for the config.json, ending up influencing the one of the final SBOM hash.

This is an issue when `gok sbom` is used to check for changes between the running instance (SBOM) and the current local instance folder, as it results in different SBOM hashes, which in these cases might mean an infinite loop of unnecessary updates.

Do you have any idea on how we could circumvent this issue?

I know @stapelberg [mentioned](https://github.com/gokrazy/tools/pull/61#issuecomment-1722529971) that ignoring the `config.InternalCompatibilityFlags` that would mean same SBOMs for an instance with differing `InternalCompatibilityFlags`, but I would prefer this poison versus having unusable SBOMs and unnecessary updates (unless we can come up with a better solution for this :)).

WDYT?

### PR DESCRIPTION
**Pull request by damdo**
Builds on top of #65 

Fixes #64 
by adopting [approach 1](https://github.com/gokrazy/tools/issues/64#issuecomment-1772664940).

Seems to be working well for all the commands I tested: sbom, update, overwrite (full,gaf).

Testing:
```
$ make gaf 2>&1 >/dev/null
$ unzip -p /tmp/disk.gaf sbom.json | jq -r '.sbom_hash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9

$ make sbom | jq -r '.sbom_hash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9

$ make overwrite 2>&1 >/dev/null # creates a full.img
$ make test & # launches a qemu test machine from the full.img at (192.168.64.2)
$ curl -sL -H 'Accept: application/json' "http://gokrazy:$PASS@192.168.64.2/" | jq -r '.SBOMHash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9

$ make update
$ curl -sL -H 'Accept: application/json' "http://gokrazy:$PASS@192.168.64.2/" | jq -r '.SBOMHash'
23c08ae3b4c009e179f46fe8e812617771c39d1540042d79c11848015dec86b9

$ vim config.json
$ git diff config.json
+++ b/config.json
@@ -7,7 +7,8 @@
     },
     "Packages": [
         "github.com/gokrazy/serial-busybox",
-        "github.com/gokrazy/breakglass"
+        "github.com/gokrazy/breakglass",
+        "github.com/gokrazy/hello"

$ make sbom | jq -r '.sbom_hash'
1ab7db66f5b0a0d3253d3e104c0b375e7ae4af7449bae635c7554e0b0b596e21

$ make update
$ curl -sL -H 'Accept: application/json' "http://gokrazy:$PASS@192.168.64.2/" | jq -r '.SBOMHash'
1ab7db66f5b0a0d3253d3e104c0b375e7ae4af7449bae635c7554e0b0b596e21
```

### CODE REVIEW

File: internal/gok/overwrite.go [hunk 1]
```diff
@@ -70,6 +70,11 @@ func (r *overwriteImplConfig) run(ctx context.Context, args []string, stdout, st
 		return err
 	}
 
+	sbom, _, err := packer.GenerateSBOM(cfg)
```
Comment (stapelberg) [inline internal/gok/overwrite.go:73]: Here and in the other GenerateSBOM() call, can you please add a comment to the tune of:

// GenerateSBOM() must be called before any modifications to cfg.InternalCompatibilityFlags, as the SBOM should reflect what’s going into gokrazy, not its internal implementation details.

**Review by stapelberg — CHANGES_REQUESTED** [review]
Looks good overall!

File: internal/gok/overwrite.go (hunk 1 above)
Comment (damdo) [reply internal/gok/overwrite.go:76]: Sure :) done

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
This breaks tests, though. Can you take a look please?

**Comment by damdo** [comment]
Yes I was just looking at it.
It throws:
```
gokrpacker_test.go:107: [overwrite --root=root.squashfs --boot=boot.fat]: open /tmp/TestGokrPacker3940063376/001/hello/builddir/github.com/gokrazy/gokrazy/go.mod: no such file or directory
```

**Review by stapelberg — APPROVED** [review]
