### PR TITLE
Fix building when GOBIN is set in the GOENV file

### LINKED ISSUE #71: /tmp/gokrazy-bins-... is not an ELF binary! read /tmp/gokrazy-bins-...: is a directory
After not upgrading my gokrazy for a year (very bad practice), I finally took the time to attempt an upgrade.

I stumbled upon the following error when running `gok update`:
```
(...)
[done] in 5.24s                        

2024/07/02 21:07:40 /tmp/gokrazy-bins-2652291663 is not an ELF binary! read /tmp/gokrazy-bins-2652291663: is a directory (perhaps running into https://github.com/golang/go/issues/53804?)
```

The mention of a `directory` looked highly suspicious (and unrelated to the linked issued). After some debugging (i.e. print statements and panics), it appears that the `Target` field is missing from the `go list -json`:
https://github.com/gokrazy/tools/blob/41f11fbe3a53695e8ad701b98ec105d4b88084b6/packer/gotool.go#L366

In my case this likely happens because I set a custom `GOBIN` in the `GOENV` file (the env var `GOVIN` gets set to an empty value by `Env()`, but this is not enough to overwrite the value written inside my `~/.config/go/env` file).

As a rough workaround, I also reset `GOENV=invalid-value` in `Env()` and it seems to be working (however it discards all my other settings, like cache location & co.)

Has anyone an idea on how to solve this in a nicer way? (if not, the empty `Target` field should be detected earlier and trigger an earlier failure).

### PR DESCRIPTION
**Pull request by oliverpool**
Fixes #71

### CODE REVIEW

File: packer/gotool_test.go [hunk 1]
```diff
@@ -0,0 +1,31 @@
+package packer
+
+import "testing"
+
+func TestPkgBasename(t *testing.T) {
+	f := func(p Pkg, wantBasename string) {
```
Comment (stapelberg) [inline packer/gotool_test.go:6]: Can you turn this into a table-driven test please? See https://go.dev/wiki/TableDrivenTests

Comment (oliverpool) [reply packer/gotool_test.go]: Done (I find [f-tests](https://medium.com/@valyala/f-tests-as-a-replacement-for-table-driven-tests-in-go-8814a8b19e9e) sometimes easier to read, but since table-driven tests are already used in the code, it is better to keep it consistent, as you proposed :)

**Review by stapelberg — APPROVED** [review]
